grafana:
  admin:
    existingSecret: grafana-admin-secret-dev
    passwordKey: admin-password
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: gp2
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 2d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'your.email@gmail.com'
      smtp_auth_username: 'your.email@gmail.com'
      smtp_auth_password: '{{ .Values.alertmanager.email.smtp_password }}'
    route:
      receiver: 'email-notifications'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10m
      repeat_interval: 1h
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'your.destination.email@example.com'
            send_resolved: true

  email:
    smtp_password:
      valueFrom:
        secretKeyRef:
          name: alertmanager-email-secret-dev
          key: smtp_password


  dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 23
      datasource: Prometheus
      label: grafana_dashboard

